from setuptools import setup, find_packages

setup(
    name="near-swarm",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "python-dotenv>=1.0.0",
        "near-api-py>=0.1.0",
        "aiohttp>=3.8.0",
        "numpy>=1.21.0",
        "pytest>=7.0.0",
        "pytest-asyncio>=0.18.0",
        "pytest-cov>=3.0.0",
        "black>=22.0.0",
        "isort>=5.10.0",
        "flake8>=4.0.0",
        "mypy>=0.950",
        "mkdocs>=1.3.0",
        "openai>=1.0.0",
        "hyperbolic>=0.1.0",
        "anthropic>=0.5.0",
        "langchain>=0.0.200",
        "transformers>=4.30.0",
        "torch>=2.0.0",
        "requests>=2.31.0",
        "websockets>=11.0.0",
        "ccxt>=4.0.0",
        "pandas>=2.0.0",
        "redis>=4.5.0"
    ],
    python_requires=">=3.8",
    author="NEAR",
    author_email="horizons@near.foundation",
    description="NEAR Swarm Intelligence",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/jbarnes850/near-swarm-intelligence",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
) 